# Use the official Nginx image from Docker Hub
FROM nginx:alpine

# Copy the public folder contents to the Nginx html folder
COPY ./public /usr/share/nginx/html

# Expose port 80 to the Docker container
EXPOSE 80
